### PR TITLE
Make UI more responsive

### PR DESCRIPTION
**Pull request by erdengk**
This PR is used to solve the display bug [it](https://github.com/polypheny/Polypheny-DB/discussions/374) mentioned.
Before modification：
WX20211214-214526

After modification：
WX20211216-091202
WX20211216-091236

### CODE REVIEW

**Comment by vogti** [comment]
Hi Kevin,
Thanks for this pull request. Unfortunately, your fix does only work for your specific monitor resolution:
Bildschirmfoto 2021-12-19 um 22 50 39
Can you make this more universal?

**Comment by erdengk** [comment]
OK, I'll try again

**Comment by erdengk** [comment]
@vogti 
Hello, I used a new way to fix this bug. Please review it. Thanks.

In the figure below, the browser window is zoomed to the minimum The foot bar is not blocked or in the wrong place.
WX20211220-203557@2x

In the figure below, the browser window is zoomed to medium The foot bar is not blocked or in the wrong place.
WX20211220-203707@2x


In the figure below, the browser window is zoomed to the maximum The foot bar is not blocked or in the wrong place
WX20211220-204124@2x

**Comment by vogti** [comment]
But now it is no longer centered if the window exceeds a certain width. Furthermore, the footer is only visible if you scroll.
Bildschirmfoto 2021-12-20 um 15 37 26

I think to fix this, it is required to calculate a max-height for the white box. Since everything is dynamic, this part needs to be dynamic as well.

**Comment by erdengk** [comment]
OK, I'll try to repair it again.

**Comment by erdengk** [comment]
Hello, I made a new modification according to your opinion.Please review it. Thanks.
The latest effect is shown in the following figures. No matter how you change the window size, the middle box is always in the middle, and you can see the footer without scrolling.

WX20211221-184136

image

About the problem you mentioned that when the maximum width is exceeded, it cannot be centered.
 I use such a solution：
In the following figure, when the window becomes larger, the button in the middle will be enlarged to the same scale and will always be in the middle.

WX20211221-183559

In the following figure, when the window width becomes large, the middle button will always be enlarged, but a navigation bar will be generated on the right side of the browser to allow users to browse down.
By the way, I modified the styles of PDB and Pui in footer so that they will not exceed the footer due to window changes.

WX20211221-184358

**Comment by erdengk** [comment]
Hi, @vogti  Maybe my method is not very good, but I am willing to continue to learn and improve it. Please give some suggestions. Thanks

**Comment by vogti** [comment]
Hi @erdengk
Sorry for the late replay. There has been a lot going on since new year. Your new approach looks much better. However, it does no longer fix the issue you have pointed out initially.

Bildschirmfoto 2022-01-10 um 12 20 21

**Comment by erdengk** [comment]
Oh, my God. Let me try to continue to fix this problem.

**Pull request closed without merging**
