### PR TITLE
Authentication for Polypheny-Control

### PR DESCRIPTION
**Pull request by VishalDalwadi**
This PR implements authentication for Polypheny-Control, trying to solve issue [291](https://github.com/polypheny/Polypheny-DB/issues/291) Authentication information is stored in `.polypheny/passwd` file. This contains the username and password. The passwords are secured using the `crypt` function. However, the password file itself isn't secured. Users may find it much easier to use different commands on their computers to secure the password file. For eg, setting the immutable flag on Linux systems using the chattr command. To add / remove / modify users the polypheny-control executable has three commands `adduser`, `remuser` and `moduser`. They will modify the password file. So, if the file is secured by users using the immutable flag, it would have to be reset before performing these operations.
Authentication can be enabled / disabled for local users by using the `localauth.enable` config.
A login page has been added to the UI to ask for credentials. If credentials are invalid or is not done, user won't be able to access the index.html page.

Closes polypheny/Polypheny-DB#291

### CODE REVIEW

**Comment by vogti** [comment]
Thank you, @VishalDalwadi, for this amazing work! This is a very valuable contribution. I have only a few very minor comments:

- The current implementation causes issues when using the REST API (using the Control Connector). The Control Connector needs to be extended to allow setting a username and password to be used for the requests.
- Authentication for the CLI commands doesn't make that much sense, especially since the commands to add more users are not protected (sure you can protect the passwd file, but it is possible to disable authentication in the config file which needs to be writable). Nevertheless, I suggest keeping this, but adding a setting for it. I see a use-case if Control is running with a different user (but this requires some other changes). I would also suggest adding an option to disable authentication entirely:
`auth.enable = true`
`auth.local = false`
`auth.cli = false`
- It would be possible to also protect the CLI commands for user management by requesting a password when at least one user is configured. This would allow the first user to be added.
- Is there a reason for not calling `writeAuthenticationDataToFile()` in the `AuthenticationDataManager`?

**Comment by VishalDalwadi** [comment]
Thanks @vogti for the kind words and for all the help you provided along the way.
1. Yes, we will need to provide the username and password there. I think the control URL itself can be used. I think if the format is `username:password@host`, basic auth header would be added. I will look into it.
2. Yeah. This would be nice.
3. Yes. Maybe, an `admin` user would be good. I can get this done.
4. Yeah. So I thought, maybe, multiple calls might be made to these methods and so every time a change is made the file is written. It was better to just make it the responsibility of the user to write those changes back. If they seem problematic, I will make those changes as well.

**Comment by VishalDalwadi** [comment]
I will make these changes. Should I make a different PR for these changes?

**Comment by vogti** [comment]
Perfect :) No, you can add the changes to this PR.

**Comment by vogti** [comment]
Hi @VishalDalwadi. Since the deadline for submitting proposals for Google Summer of Code is approaching, I wanted to ask you if you have any questions regarding writing the proposal. As you may have seen, we have created a template you can use for your proposal. As you may have seen, we have created a template you can use for your proposal. It is linked on our [website](https://polypheny.org/community/gsoc/). I am contacting you this way as I do not have a mail address from you. Please contact us (mail (at) polypheny.org) if you have any questions about writing the proposal. We are already looking forward to your proposal.

**Comment by VishalDalwadi** [comment]
Thank you, @vogti for the support. I am still working on my proposal. I plan to submit it as soon as possible. So far I have no questions. But thank you for asking. I am looking forward to working with you.

**Comment by VishalDalwadi** [comment]
I have made the relevant changes.
  1. Created different configuration options for cli, local authentication and authentication as a whole.
  2. Made some changes to require an admin user to create/add/delete users. (The passwd file however can be modified easily; It needs to be secured by some other way.)
  3. Modified PolyphenyControlConnector to take in ClientData.

**Comment by VishalDalwadi** [comment]
`reference.conf` had `auth.local` disabled. So, here I have enabled it, so that it can be tested. I have tested it to work even if auth.local is disabled. However, maybe we can make some changes to the workflow to check both versions.
Also added `control.sessionTimeout` which takes session timeout in seconds. I have set it to 1000 so that the session timeout handling code also gets tested.
Rest of all is just refactorings.

**Comment by vogti** [comment]
Thank you very much for this great contribution! I have a few suggestions how it can be improved even further:

- The tests are failing on Windows. 
- Can you please add the license header to the following files: `AuthenticationDataManager.java`, `AuthenticationFileManager.java`, `AuthenticationManager.java`, `NotificationManager.java`.
- The `auth.local` setting should be set to false on default. This makes it significantly easier to get started with Polypheny Control. Regarding the test, I have a suggestion below.
- Executing the unit tests creates a security hole (it creates a pc user with PC as password). In order to avoid this, I would suggest first renaming an existing `passwd` file and then restore it after the tests. The issue is making sure that this happens even if there are issues with executing the tests. In Polypheny-DB this issue is solved using a test mode. You can consider introducing something similar for Control. If started with the testing argument, an existing passwd could be renamed to `passwd.backup`. If started without the testing argument, the system could first check if there is a `.backup` file and if so, delete an existing `passwd` file and rename the `passwd.backup` file to `passwd`. Something similar can be done for the configuration file.
- It would be good if you can write a few lines of documentation on how to manage users (we can put this in the documentation section of the website). Furthermore, it would make sense to add a few sentences to the README file.
- With a special configuration for testing it would also be possible to increase the default session timeout.

Nice to have, further ideas:
- The design of the login page can be adjusted to better match the design of the rest of the dashboard.
- It would be nice if the users can also be managed in the dashboard.

**Comment by VishalDalwadi** [comment]
Thank you, @vogti . I will look into those issues.

**Comment by vogti** [comment]
There is a [new pull request](#14).

**Pull request closed without merging**
