### PR TITLE
Responsive Polypheny-Control UI

### PR DESCRIPTION
**Pull request by prinsusinghal**
I have made the Polypheny-Control UI responsive. Thus, the page will not be distorted when viewed on smaller screens.

Fixes polypheny/Polypheny-DB#295

### CODE REVIEW

**Review by vogti — CHANGES_REQUESTED** [review]
Thank you very much for this pull request. There are some issues:
- The circles get oval on larger screens now. This can be "fixed" by removing the `max-width: 1500px;` setting in `.main`, but I would prefer a solution which allows to keep this max-width setting.
- Footer is no longer at the bottom of the page.
- The distance between the two rows is not adjusted dynamically (on very large screens they might even overlap).
- There is now some margin on the left- and right side of the footer.
- There have unnecessary indentations been added in `index.html`.

Screenshot 2021-03-15 at 18 54 06
Screenshot 2021-03-15 at 19 02 25

**Comment by prinsusinghal** [comment]
sure. I am working on them.

**Comment by prinsusinghal** [comment]
@vogti , I have resolved the issues that you listed. Please review them.

**Comment by vogti** [comment]
This looks very good. It's very nice that you now made everything responsive. There is only one minor issue: The footer is now always at the bottom of the page, but it often requires scrolling. The reason for this is, that you made the font size of the heading dependent from the window size. Since the font size influences the line height, your calculated min-height for the main-div wrong is in most of the cases.

**Comment by prinsusinghal** [comment]
@vogti , I calculated the margin between heading and top of the page which I found close to 3.5vw in most of the cases. Thus I used this calculation in setting the min-height of main classs. Now the footer is at the bottom of the page and it does NOT require scrolling.

**Comment by vogti** [comment]
Nice :) The page is still a few pixels larger than the window size (at least in Firefox) but if you have no idea how to fix this, I would be ok with merging it. It is a very minor thing.
I like that you also made the footer responsive. One suggestion: What do you think about reducing the font size in the footer to `1vw` and making also the line-height in `#footer-middle` responsive? I would suggest `line-height: 1.6vw;`.

**Comment by prinsusinghal** [comment]
Yes, it looks better after reducing the font size in the footer to 1vw and making the line-height in footer-middle responsive. Regarding page larger than the window size, I searched that it is a problem in Firefox browser as can be seen [here](https://support.mozilla.org/en-US/questions/1176030) and thus there is nothing much that can be done from our side to solve this problem. Since I used chrome, I didn't found any such issue.

**Review by vogti — APPROVED** [review]
Thx @prinsusinghal for this contribution!

**Comment by prinsusinghal** [comment]
@vogti Thank you very much. Glad to work with you and contributing to polypheny.

**Pull request merged**
